services:
  web:
    image: p988744/hylove-demo:latest
    ports:
      - "80:80"
    environment:
      - ENABLE_AUTH=true
      - REACT_APP_ANALYSIS_API_BASE=/
    restart: always
    volumes:
      - "${HTPASSWD_PATH:-./.htpasswd}:/etc/nginx/.htpasswd:ro"